using Domain;
using MediatR;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Persistence;

namespace Application.Tickets.Commands;

public class CreateTicket
{
    public class Command : IRequest<string>
    {
        public required Ticket Ticket { get; set; }
    }

    public class Handler(AppDbContext context) : IRequestHandler<Command, string>
    {
        public async Task<string> Handle(Command request, CancellationToken cancellationToken)
        {
            context.Tickets.Add(request.Ticket); // Not getting value generated by database so no async
            
            await context.SaveChangesAsync(cancellationToken);
            
            return request.Ticket.Id;
        }
    }
}